### ISSUE TITLE
Error sending or receiving any file.

### ISSUE THREAD

**Issue by sserantes** [kontalk/androidclient#677]
Kontalk 3.1.5 - Android 5.1.1
I cannot send or receive any file, I have no issues sending text messages.
I only get an error message sending or receiving attached file.

**Comment by dario-chiappetta** [comment]
I've been having the same issue for a couple of days now (Kontalk 3.1.5, Cyanogen 12.1.1, Oneplus One), I think the bug appeared with 3.1.4, but I can't be 100% sure. Attachments seem to work when I'm on **mobile** network, but no way of uploading or downloading on **WiFi**. This goes for voice messages as well, so this may be a duplicate of #676.

This is what logcat says when I try and download an attachment:

```
D/MessageCenterService(12113): starting foreground progress notification
E/MessageCenterService(12113): download error
E/MessageCenterService(12113): javax.net.ssl.SSLHandshakeException: Handshake failed
E/MessageCenterService(12113): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
E/MessageCenterService(12113): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
E/MessageCenterService(12113): 	at com.android.okhttp.Connection.connect(Connection.java:155)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
E/MessageCenterService(12113): 	at org.kontalk.client.ClientHTTPConnection._download(ClientHTTPConnection.java:202)
E/MessageCenterService(12113): 	at org.kontalk.client.ClientHTTPConnection.downloadAutofilename(ClientHTTPConnection.java:195)
E/MessageCenterService(12113): 	at org.kontalk.service.DownloadService.onDownloadURL(DownloadService.java:191)
E/MessageCenterService(12113): 	at org.kontalk.service.DownloadService.onHandleIntent(DownloadService.java:136)
E/MessageCenterService(12113): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/MessageCenterService(12113): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/MessageCenterService(12113): 	at android.os.Looper.loop(Looper.java:135)
E/MessageCenterService(12113): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/MessageCenterService(12113): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xaec3da00: Failure in SSL library, usually a protocol error
E/MessageCenterService(12113): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xab9c2c4d:0x00000000)
E/MessageCenterService(12113): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/MessageCenterService(12113): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
E/MessageCenterService(12113): 	... 17 more
D/audio_hw_primary(  238): out_standby: enter: stream (0xb5880740) usecase(1: low-latency-playback)
D/hardware_info(  238): hw_info_append_hw_type : device_name = speaker
```

Upload error looks similar:

```
E/MessageCenterService(12113): upload error
E/MessageCenterService(12113): java.io.IOException: upload error
E/MessageCenterService(12113): 	at org.kontalk.upload.KontalkBoxUploadConnection.innerException(KontalkBoxUploadConnection.java:182)
E/MessageCenterService(12113): 	at org.kontalk.upload.KontalkBoxUploadConnection.upload(KontalkBoxUploadConnection.java:143)
E/MessageCenterService(12113): 	at org.kontalk.service.UploadService.onHandleIntent(UploadService.java:175)
E/MessageCenterService(12113): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/MessageCenterService(12113): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/MessageCenterService(12113): 	at android.os.Looper.loop(Looper.java:135)
E/MessageCenterService(12113): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/MessageCenterService(12113): Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
E/MessageCenterService(12113): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
E/MessageCenterService(12113): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
E/MessageCenterService(12113): 	at com.android.okhttp.Connection.connect(Connection.java:155)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
E/MessageCenterService(12113): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
E/MessageCenterService(12113): 	at org.kontalk.upload.KontalkBoxUploadConnection.upload(KontalkBoxUploadConnection.java:135)
E/MessageCenterService(12113): 	... 5 more
E/MessageCenterService(12113): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x9da0b200: Failure in SSL library, usually a protocol error
E/MessageCenterService(12113): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xab9c2c4d:0x00000000)
E/MessageCenterService(12113): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/MessageCenterService(12113): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
E/MessageCenterService(12113): 	... 15 more
```

**Comment by daniele-athome** [comment]
I've updated the cipher set on the server, could both you try again please?

**Comment by daniele-athome** [comment]
Should be fixed by 1900f2eea6db5b20b67626dd46334e6ae2e4c9b5. Feel free to reopen if it still happens on 3.1.6 (releasing tonight).

**Comment by dario-chiappetta** [comment]
Unfortunately the bug is still there for me in 3.1.6, with the same stack traces. It's failing on a SSLv3 handshake: isn't SSLv3 evil?

One thing I noticed is that the behavior does depend on the network: couple of days ago (Kontalk 3.1.5) my phone connected to a random open hotspot while I was walking, and there the attachments were working.

**Comment by daniele-athome** [comment]
I had to keep SSLv3 for old clients (although the server is capable of TLS1.2). Anyway, I don't know if it's just a log printing "SSL23" while in fact is doing TLS handshake (source code may be shared in some points, the two protocols are similar).

About the issue only happening on some networks: the file server runs on port 5980, maybe some filter/firewall/restriction on your network causing dropping the connection? It's really weird that one network worked and the other did not.

May I see the detailed SSL error line please? Is it **exactly** the same?

**Comment by dario-chiappetta** [comment]
Yes the two logs are exactly the same (but for memory locations and line numbers of course), here they are:


download
```
E/MessageCenterService( 4678): download error
E/MessageCenterService( 4678): javax.net.ssl.SSLHandshakeException: Handshake failed
E/MessageCenterService( 4678): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
E/MessageCenterService( 4678): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
E/MessageCenterService( 4678): 	at com.android.okhttp.Connection.connect(Connection.java:155)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
E/MessageCenterService( 4678): 	at org.kontalk.client.ClientHTTPConnection._download(ClientHTTPConnection.java:200)
E/MessageCenterService( 4678): 	at org.kontalk.client.ClientHTTPConnection.downloadAutofilename(ClientHTTPConnection.java:193)
E/MessageCenterService( 4678): 	at org.kontalk.service.DownloadService.onDownloadURL(DownloadService.java:191)
E/MessageCenterService( 4678): 	at org.kontalk.service.DownloadService.onHandleIntent(DownloadService.java:136)
E/MessageCenterService( 4678): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/MessageCenterService( 4678): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/MessageCenterService( 4678): 	at android.os.Looper.loop(Looper.java:135)
E/MessageCenterService( 4678): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/MessageCenterService( 4678): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x99598000: Failure in SSL library, usually a protocol error
E/MessageCenterService( 4678): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xaba3ac4d:0x00000000)
E/MessageCenterService( 4678): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/MessageCenterService( 4678): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
E/MessageCenterService( 4678): 	... 17 more
```

upload
```
E/MessageCenterService( 4678): upload error
E/MessageCenterService( 4678): java.io.IOException: upload error
E/MessageCenterService( 4678): 	at org.kontalk.upload.KontalkBoxUploadConnection.innerException(KontalkBoxUploadConnection.java:180)
E/MessageCenterService( 4678): 	at org.kontalk.upload.KontalkBoxUploadConnection.upload(KontalkBoxUploadConnection.java:141)
E/MessageCenterService( 4678): 	at org.kontalk.service.UploadService.onHandleIntent(UploadService.java:175)
E/MessageCenterService( 4678): 	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
E/MessageCenterService( 4678): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/MessageCenterService( 4678): 	at android.os.Looper.loop(Looper.java:135)
E/MessageCenterService( 4678): 	at android.os.HandlerThread.run(HandlerThread.java:61)
E/MessageCenterService( 4678): Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
E/MessageCenterService( 4678): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:390)
E/MessageCenterService( 4678): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:201)
E/MessageCenterService( 4678): 	at com.android.okhttp.Connection.connect(Connection.java:155)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:106)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:217)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
E/MessageCenterService( 4678): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
E/MessageCenterService( 4678): 	at org.kontalk.upload.KontalkBoxUploadConnection.upload(KontalkBoxUploadConnection.java:133)
E/MessageCenterService( 4678): 	... 5 more
E/MessageCenterService( 4678): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xaeda3400: Failure in SSL library, usually a protocol error
E/MessageCenterService( 4678): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xaba3ac4d:0x00000000)
E/MessageCenterService( 4678): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
E/MessageCenterService( 4678): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318)
E/MessageCenterService( 4678): 	... 15 more
```

I find weird as well that one network in particular was working. I would be surprised if it was a problem with my network though, because I've tried a couple so far, and that one was the only one I could use attachments with (and I never had troubles with attachments up to the past week). Also, nmap tells me that port 5980 is open on beta.kontalk.org, so it looks reachable.

**Comment by daniele-athome** [comment]
I started having reports about this when I switched to HttpsUrlConnection because Google was deprecating HttpClient. I can't explain why it's working on that particular network, but until you said that I was pretty sure it was a SSL handshake problem, most probably related to server and client not agreeing on the cipher or something like that (I'm really not an expert on the subject).
Now, some late night hacking: could you try now please?

**Comment by dario-chiappetta** [comment]
Still not working for me

**Comment by sserantes** [comment]
Neither for me.

**Comment by TheLastProject** [comment]
Unfortunately, I still have issues with 3.1.6 too:
```
04-16 15:21:49.160  5907 13956 E MessageCenterService: download error
04-16 15:21:49.160  5907 13956 E MessageCenterService: javax.net.ssl.SSLHandshakeException: Handshake failed
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:396)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.Connection.connect(Connection.java:143)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:185)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:437)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:388)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:501)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at org.kontalk.client.ClientHTTPConnection._download(ClientHTTPConnection.java:200)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at org.kontalk.client.ClientHTTPConnection.downloadAutofilename(ClientHTTPConnection.java:193)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at org.kontalk.service.DownloadService.onDownloadURL(DownloadService.java:191)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at org.kontalk.service.DownloadService.onHandleIntent(DownloadService.java:136)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at android.os.Handler.dispatchMessage(Handler.java:102)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at android.os.Looper.loop(Looper.java:148)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at android.os.HandlerThread.run(HandlerThread.java:61)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
04-16 15:21:49.160  5907 13956 E MessageCenterService:          ... 21 more
04-16 15:21:49.160  5907 13956 E MessageCenterService:          Suppressed: javax.net.ssl.SSLHandshakeException: Connection closed by peer
04-16 15:21:49.160  5907 13956 E MessageCenterService:                  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
04-16 15:21:49.160  5907 13956 E MessageCenterService:                  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
04-16 15:21:49.160  5907 13956 E MessageCenterService:                  ... 20 more
04-16 15:21:49.160  5907 13956 E MessageCenterService:  Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x9ee2a000: Failure in SSL library, usually a protocol error
04-16 15:21:49.160  5907 13956 E MessageCenterService: error:100c543e:SSL routines:ssl3_read_bytes:TLSV1_ALERT_INAPPROPRIATE_FALLBACK (external/boringssl/src/ssl/s3_pkt.c:972 0x9cd38a00:0x00000001)
04-16 15:21:49.160  5907 13956 E MessageCenterService:          at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
04-16 15:21:49.160  5907 13956 E MessageCenterService:          at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
04-16 15:21:49.160  5907 13956 E MessageCenterService:          ... 20 more
04-16 15:21:49.160  5907 13956 E MessageCenterService: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake terminated: ssl=0x9ee2a000: Failure in SSL library, usually a protocol error
04-16 15:21:49.160  5907 13956 E MessageCenterService: error:100c543e:SSL routines:ssl3_read_bytes:TLSV1_ALERT_INAPPROPRIATE_FALLBACK (external/boringssl/src/ssl/s3_pkt.c:972 0x9cd38a00:0x00000001)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
04-16 15:21:49.160  5907 13956 E MessageCenterService:  ... 20 more
```

**Comment by webratte** [comment]
Me to in GSM. In Wi-Fi it works.
I use the current Alpha V 3.1.7- preview (106).

**Comment by webratte** [comment]
It seams I have this problem only for pictures.
Audio messages work. Up and download.

**Comment by webratte** [comment]
Me again 😉
After a few test I found out for me - only Upload dosn't work.
(New)Downlod of pictures which I have already received, works.

**Comment by daniele-athome** [comment]
Ok I give up. Seriously, I've tried **everything**, on both client and server: switching chiper sets, trying different protocols, tons of other tries. It always come up to broken SSL implementations (I still have to understand whose fault is: server or client, but whatever), probably when parsing the Kontalk X.509 bridge certificate which is used by the app to authenticate against the Kontalk file server.
kontalk/specs#12 would have been on the way soon, I guess it must be now (it removes the need for this X.509 trick). I'm sorry guys. I'll try to speed this up to produce something in one or two days.

**Comment by svrnwnsch** [comment]
@daniele-athome Thank you for your work

BTW I can confirm @dario-chiappetta discovery that the bug seems to be network dependent.

**Comment by daniele-athome** [comment]
> BTW I can confirm @dario-chiappetta discovery that the bug seems to be network dependent.

Well, even if his specific problem is network dependent, the SSL issue is a much larger which should be finally resolved by 3.1.7 (releasing between tonight and tomorrow night). There is lighttpd now in front of the upload server, it should be compatible with any client you throw at it.

**Comment by daniele-athome** [comment]
Also, please note that files sent with 3.1.7 won't be able to be downloaded by older clients (and vice-versa). Upgrading fix the issue (files that failed to download can still be downloaded after upgrading).

**Comment by sserantes** [comment]
Thanks for all your work, much appreciated!

**Comment by webratte** [comment]
It seams it's not fixed yet in current v.3.1.7

If I send a picture to myself, the upload faild.
I have not yet tested in Wi-Fi.

**Comment by webratte** [comment]
Just in Wi-Fi tested.
In Wi-Fi it works fine. (Up- and Download)

**Comment by daniele-athome** [comment]
This is getting weirder every day. @webratte can you produce a logcat please? I don't remember if you have root access or the SDK installed on your computer.

**Comment by webratte** [comment]
Sorry, no root.
        But I can trie install SDK. But I'm to stupid for create a logcat.
        
        Do you know a goot tutorial for that?
      
    On 19.04.2016 18:43, Daniele Ricci
      wrote:
    
    
      This is getting weirder every day. @webratte
        can you produce a logcat please? I don't remember if you have
        root access or the SDK installed on your computer.
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub

**Comment by webratte** [comment]
@TheLastProject Have you this problem too with the current version?
Maybe you can create a logcat. You have more technical skills then me.

**Comment by TheLastProject** [comment]
I actually don't have any issues. The file sending and receiving works fine for me and much faster than it ever did before. If I do run into issues, I will create a logcat, though.

**Comment by daniele-athome** [comment]
@webratte what Android version do you have again? If < 4.2 you can work it without root.
Note to myself: use ACRA damn it :D

**Comment by webratte** [comment]
@daniele-athome I know.
    But I have Version 5.0
    
    Is there a easy way to implement a option for reading and sending a
    Log?
    I have seen this in other apps.
    
    Or is this what you mean with ACRA?
    
    On 19.04.2016 19:42, Daniele Ricci
      wrote:
    
    
      @webratte what Android version do you
        have again? If < 4.2 you can work it without root.
        Note to myself: use ACRA damn it :D
      —
        You are receiving this because you were mentioned.
        Reply to this email directly or view
          it on GitHub

**Comment by daniele-athome** [comment]
@webratte you are running the Google Play version right?

**Comment by webratte** [comment]
Yes, I use the Google Play Version.

**Comment by daniele-athome** [comment]
Great. If you subscribe to the beta program you'll find a new version (3.1.8-preview) integrated with Crashlytics that will send an automatic report of the issue.

**Comment by webratte** [comment]
It's already installed.
Have I to do something?
Or just trie to send a picture?
I just did it and upload failed of course.

**Comment by daniele-athome** [comment]
Yes just like that. It should be sending a report automatically to Crashlytics. I've just tried a simulated upload error (switched to airplane mode while sending) and the report came a few minutes later.
I guess you don't have like adblockers or AdAway or something like that blocking analytics sites (the latter would require root anyway).

By the way, does the in progress notification appear first for a few moments and **then** the upload error notification or is it the upload notification popping up before everything? Can you notice that please? It shouldn't be related to this issue, but I want be sure of that.

**Comment by webratte** [comment]
First I have the "sending" notification for a minute or so.
Then I got the "upload failed" message.

I have no Add blockers. 

But a Antivir App:
https://play.google.com/store/apps/details?id=com.avira.android

But I don't belive that it blocks it.
Or what do you think?

You got no log from me yet?

**Comment by daniele-athome** [comment]
Ok I got it now. It took some time :-)
It is a SocketTimeoutException, so it's indeed a network problem...
Can you connect to this url https://zeta.kontalk.net/test using your phone browser from mobile network? You should get a 404 - Not Found error (that error specifically please, other errors should not appear).

**Comment by webratte** [comment]
Yes, I got instantly this error message.

And nothing else.

**Comment by daniele-athome** [comment]
It is strange that it happens only from within Kontalk and it works in the browser instead.
@dario-chiappetta did you bump into this issue with 3.1.7 or later?

I'm almost out of options...

**Comment by webratte** [comment]
@daniele-athome If I can do something please let me know.
I need this feature. 

BTW: Shouldn't we reopen this issue?
Just for remember it ;-)

**Comment by daniele-athome** [comment]
@webratte your issue is really one of a kind. It is not a certificate or SSL problem because it works on WiFi. It's not a network problem (e.g. firewall) because you can access it on your phone browser.
It's also not a server problem because of the above reasons.
One last thing you could try is another device on the same network (best if tried with the same mobile carrier).

**Comment by daniele-athome** [comment]
You probably already know that: you can simply export and import your key to the other device to clone the same account, no need for registering from scratch again.

**Comment by webratte** [comment]
My wife an my son uses the same GSM provider then I.
I will check it on there phones and there Kontalk accounts.

If it's work on there phones I will import one of this accounts to my phone.
We will see what happens.

I will report it very soon.

**Comment by webratte** [comment]
Ok, just tested on my sons and my wifes phone and there accounts (Current Google Play Version of Kontalk).
The same issue, upload faild after a while.

After switch to Wi-Fi the upload works.

**Comment by daniele-athome** [comment]
So all of you using the same carrier have the same problem. Good, it means it's not only you at least :-)
Another idea just came to my mind: automatic proxy in the APN settings or transparent proxy by the mobile carrier (which is not supported by Kontalk itself, but it should be injected automatically by Android if using their API for HTTP, IIRC). You could check:

* APN settings from Android (System settings > More... > Mobile networks > Access Point Names, please paste here all settings or a screenshot)
* Access this from your mobile network in a browser and report the result: http://www.lagado.com/proxy-test or this http://amibehindaproxy.com/

Thanks for your patience. Let's get this over with! :-)

**Comment by webratte** [comment]
First the Proxy test result:
My IP I have cleaned 😉

If you need it, you will get it.

#######################

Proxy Test

This request appears NOT to have come via a proxy.

The request appears to have originated from host tmo-097-153.customers.d1-online.com which has ip address 80.###.##.###

 

The Lagado Proxy Test shows details of any proxy servers you are using. It is especially useful to expose transparent proxies. These are proxies inserted between your browser and the web, typically by your ISP, and often without you knowing.

Sometimes a proxy will be deliberately hidden so it won't be exposed by this test. In this case you can use the Cache Test to expose stealthed transparent proxy caches.

 
The Raw Details

Here are the raw details of the request received by this server.

Remote   Host tmo-097-153.customers.d1-online.com   IP Address 80.###.##.###

Request   Protocol HTTP/1.1   Method GET
Request Headers
User-Agent	Mozilla/5.0 (Android 5.0; Mobile; rv:45.0) Gecko/45.0 Firefox/45.0
Accept	text/html,​application/xhtml+xml,​application/xml;q=0.9,​*/*;q=0.8
Accept-Language	de,de-DE;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding	gzip, deflate
DNT	1
Host	www.lagado.com
Cache-Control	max-age=43200
Connection	keep-alive

This Server   Host www.lagado.com   IP Address 27.131.76.84

Date: Saturday 23 Apr 2016 0:02:20 GMT+1000

Please Note: The conclusion that the request did not come via a proxy is based on the absense of the Via, Forwarded, X-Forwarded-For and Client-ip headers. It is still possible that a proxy is handling the request without announcing itself in the recommended way. (see rfc2616 & draft-ietf-http-v10-spec-01 & Squid Configuration Guide & Squid Release Notes 1.1)

**Comment by webratte** [comment]
And here the APN's

**Comment by daniele-athome** [comment]
> And here the APN's

Forgot something? :-)

**Comment by webratte** [comment]
Dont't hurry 😉
Now there should be a screenshot.

**Comment by daniele-athome** [comment]
Please click the selected APN to get the details, that's where the proxy should be configured or not.

**Comment by webratte** [comment]
There is no proxy defined.
If I'm Home again I give you more Infos.

BTW: In K-9 Mail sending Mails with attached pictures faild also.

Maybe it's the same problem or simply because slow connection.

**Comment by daniele-athome** [comment]
Kontalk currently has a 40s timeout on send/receive data and a 15s timeout on connect, both hard-coded.
A timeout could happen with a 2G connection, but if you can get a stable 3G connection it should work.

**Comment by daniele-athome** [comment]
The send/receive timeout is intended fromt the last sent byte, not the whole transmission.

**Comment by webratte** [comment]
My Provider reduce speed after I use more then 100 MB traffic.
At the moment I have only slow connection.
But in older Kontalk versions there was no problem with this(and should not be because very often there is bad connection). The upload was always fast enough.

**Comment by webratte** [comment]
Can you provide a Version (in Google Play Beta Chanel) with longer timeout?
So we could trie if this is the problem.

Or will this not be helpfull?

**Comment by daniele-athome** [comment]
Yes, I'm going to publish a new alpha release to Google Play with 4 times the values (2m read timeout, 1min connect timeout).
Do you have the same problem with audio messages too? Especially shorter ones should be very small (like < 50 KB).

**Comment by webratte** [comment]
I become crazy.
Now both (Audio and Picture) works....

I will see what will hsppens tomorrow.

**Comment by webratte** [comment]
I just walkt around for better and less better connection.
Sometimes it works, sometimes not.

Let's trie the Version with longer timeout.
I will report after testing a few houres and different places.

**Comment by webratte** [comment]
@daniele-athome I did a few tests with the current alpha (3.1.8-(111)). Also with really bad connection.
Upload pictures up to +/-100 kB works fine.

I will keep on testing.

Pictures send in original size from camera (+/- 2 MB) failed.
Maybe you could extend time out time???

In this case  we would need a way to cancel running uploads of course.

I think a way to cancel up/downloads via click on notification (or however) would be a good idea anyway.

If you like I'll open a new issue for that.

**Comment by daniele-athome** [comment]
@webratte you can cancel an ongoing upload by deleting the message itself.

About your connection problems: I'm beginning to think that your mobile carrier is cutting out long lived connections or (most probably) big data transfer. No matter how long I set the timeout.
To prove that, can you take take note of the time required to timeout? Also how much progress do you get in the upload notification when it times out? It doesn't need to be a precise percentage value.

**Comment by webratte** [comment]
Thank you.

I'm glad to see it's not really a Kontalk issue. 
And more glad, you still can fix it 😀

From start upload to "upload faild" message it took round about 4 minutes for 4 MB picture.

Ok Most time I use redused size Medium 0,8 MP in Kontalk settings.
But sometimes I need the full quality.

**Comment by daniele-athome** [comment]
What about the upload progress on the 4 MB picture? Did it moved at all?
I'm afraid your carrier is just cutting out the connection at some point of their own discretion.

**Comment by webratte** [comment]
The status bar in notification shows "full" after a few seconds and stay
so until "upload faild" message appeares.

Just tried with a good conection. It works.
Maybe my bad connection (into the forest) is simply to instable and
breaks off for a moment.
So I can life with it.

**Comment by daniele-athome** [comment]
I'm sorry but this is clearly a network issue. Especially when you say that also attachments in e-mail have the same issue. I can't really do anything :-( I think you should contact your carrier to let them know about this issue though.

**Comment by webratte** [comment]
Sorry I was wrong. I forgot to set Picture size to "original" for my test.

Anyway I think there more important things to do e.g Group Chat ;-)
Especially I belive your right and it's a carrier issue.

Still thank you very much for your work on this issue and of course for
Kontalk.

Now let's concentrate to the really important things.

I'll do my best as critical tester :-)
